export const elFactoEditorialConfig = {
  organization: {
    name: "El Facto",
    handle: "@elfactonoticias",
    primaryMarket: "México",
    dailyPublishingTarget: 15,
    primaryInputChannel: "instagram",
  },
  purpose: [
    "investigar",
    "analizar",
    "desmentir información errónea",
    "entregar datos reales, relevantes y verificados",
    "fomentar pensamiento crítico y apertura al diálogo",
  ],
  coveragePriorities: [
    "política mexicana",
    "acontecimientos internacionales con impacto ciudadano",
    "derechos",
    "desigualdad",
    "instituciones y poder",
    "economía cotidiana",
    "cultura",
    "verificación de información viral",
  ],
  structuralQuestions: [
    "¿Quién tomó la decisión?",
    "¿A quién beneficia?",
    "¿Quién absorbe el costo?",
    "¿Qué derechos están involucrados?",
    "¿Qué personas o comunidades no están representadas?",
    "¿Qué evidencia respalda la afirmación?",
    "¿Qué sigue sin conocerse?",
  ],
  voice: {
    attributes: ["clara", "firme", "accesible", "crítica", "contextual", "no condescendiente"],
    avoid: [
      "propaganda partidista",
      "sensacionalismo",
      "atribuciones vagas",
      "adjetivos presentados como evidencia",
      "lenguaje oficial reproducido como neutral",
      "certeza falsa",
    ],
  },
  verificationStatuses: [
    "confirmed",
    "corroborated",
    "developing",
    "misleading",
    "false",
    "unverifiable",
    "needs_review",
  ],
  people: [
    { id: "nadia-valentina-baez", name: "Nadia Valentina Báez Patiño", role: "Directora de Medios", aliases: ["Valentina"], requiresAliasConfirmation: true },
    { id: "esmeralda-ortega", name: "Esmeralda Ortega Jiménez", role: "Directora creativa", aliases: [] },
    { id: "pavel-martinez", name: "Pavel Martínez Gaona", role: "Creador de contenido", aliases: ["Pavel"] },
    { id: "alejandro-de-loza", name: "Alejandro de Loza García", role: "Director Jurídico y Compliance", aliases: [] },
    { id: "jose-jesus-lopez-lagos", name: "José Jesús López Lagos", role: "Director Creativo", aliases: ["Lagos"] },
    { id: "ilse-reyes", name: "Ilse Mariana Reyes Valle", role: "Directora de Información", aliases: ["Ilse"] },
  ],
  aiGuardrails: {
    requireHumanApproval: true,
    allowAutomaticPublishing: false,
    allowAutomaticColumnSignature: false,
    allowFaceRecognitionForAuthorship: false,
    requireSourceAttribution: true,
    exposeUncertainty: true,
    preserveCorrections: true,
  },
} as const;

export type ElFactoEditorialConfig = typeof elFactoEditorialConfig;
